###############################################################################
# $Id: Makefile,v 1.1.1.1 2004-12-13 19:09:20 deronj Exp $
###############################################################################

SUB_DIRS = ASTsupport \
	calc \
	exprAST \
	filter \
	filterWithRule \
	flexLexer \
	heteroAST \
	HTML \
	IDL \
	imagNodeAST \
	includeFile \
	tinyc \
	inherit.tinyc \
	java \
	lexRewrite \
	multiLexer \
	multiParser \
	parseBinary \
	preserveWhiteSpace \
	transform \
	treewalk \
#	unicode

ALL_SUB_DIRS = $(SUB_DIRS)

ifndef TOPDIR
TOPDIR  = $(shell pwd)/../..
endif

include $(TOPDIR)/scripts/Config.make
include $(TOPDIR)/scripts/Rules.make
