###############################################################################
# $Id: Makefile,v 1.1.1.1 2004-12-13 19:08:46 deronj Exp $
###############################################################################

SUB_DIRS = cpp
ALL_SUB_DIRS = $(SUB_DIRS)

ifndef TOPDIR
TOPDIR  = $(shell pwd)/..
endif

include $(TOPDIR)/scripts/Config.make
include $(TOPDIR)/scripts/Rules.make
